### PR TITLE
Add events endpoint

### PR DESCRIPTION
**Pull request by ezwang**
Add `/events/<type>` endpoint for retrieving events to be shown in the PennMobile application.

### CODE REVIEW

**Comment by joshdoman** [comment]
Looks great! Couple comments, the website URL, email, and facebook URL should be nullable since they are optional. Additionally, is the email that they are providing one that should be accessible from the app (public contact email)?

**Comment by ezwang** [comment]
Currently the email is the contact email that we collect. You can decide not to show this field in the app.

It should be fine to have the fields as non-null. We can represent no data given by having an empty string, which is different from null.

**Comment by joshdoman** [comment]
If it's not too hard, I think that it would be cleaner to have the fields as nullable because we already check for null on the client and it would be an extra check to verify the string is not empty. As long as we're explicit on the form that this is an email for us to quickly reach them, I think we can leave the email field as is.

**Comment by ezwang** [comment]
Changed website and facebook fields to return null if there is no user input.

**Pull request merged**
